// This file is auto generated by polygo
package repositories

import (
	"github.com/MarcelArt/multi-tenant-system/models"
	"github.com/gofiber/fiber/v2"
	"github.com/morkid/paginate"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type IOrgCrudRepo[TModel any, TDto models.IDTO, TPage any] interface {
	Create(input TDto) (uint, error)
	Read(c *fiber.Ctx, orgID any, dest []TPage) paginate.Page
	Update(id any, orgID any, input *TDto) error
	Delete(id any, orgID any) (TModel, error)
	GetByID(id any, orgID any) (TModel, error)
}

type OrgCrudRepo[TModel any, TDto models.IDTO, TPage any] struct {
	db        *gorm.DB
	pageQuery string
}

func NewOrgCrudRepo[TModel any, TDto models.IDTO, TPage any](db *gorm.DB) *OrgCrudRepo[TModel, TDto, TPage] {
	return &OrgCrudRepo[TModel, TDto, TPage]{
		db: db,
	}
}

func (r *OrgCrudRepo[TModel, TDto, TPage]) Create(input TDto) (uint, error) {
	err := r.db.Create(&input).Error

	return input.GetID(), err
}

func (r *OrgCrudRepo[TModel, TDto, TPage]) Read(c *fiber.Ctx, orgID any, dest []TPage) paginate.Page {
	pg := paginate.New()

	query := r.db.Raw(r.pageQuery, orgID)
	page := pg.With(query).Request(c.Request()).Response(&dest)

	return page
}

func (r *OrgCrudRepo[TModel, TDto, TPage]) Update(id any, orgID any, input *TDto) error {
	return r.db.Model(input).Where("id = ? and organization_id = ?", id, orgID).Updates(input).Error
}

func (r *OrgCrudRepo[TModel, TDto, TPage]) Delete(id any, orgID any) (TModel, error) {
	var model TModel
	err := r.db.Clauses(clause.Returning{}).Where("id = ? and organization_id = ?", id, orgID).Delete(&model).Error

	return model, err
}

func (r *OrgCrudRepo[TModel, TDto, TPage]) GetByID(id any, orgID any) (TModel, error) {
	var model TModel
	err := r.db.Where("id = ? and organization_id = ?", id, orgID).First(&model).Error
	return model, err
}
