// This file is auto generated by polygo
package repositories

import (
	"github.com/MarcelArt/multi-tenant-system/models"
	"gorm.io/gorm"
)

const userPageQuery = `
	select 
		username, 
		email
	from users
	where deleted_at is null
`

type IUserRepo interface {
	IBaseCrudRepo[models.User, models.UserDTO, models.UserPage]
	GetByUsernameOrEmail(username string) (models.UserDTO, error)
	GetOrgPermissions(id any, orgID any) ([]string, error)
	GetPermissions(id any) ([]models.OrganizationPermissionClaims, error)
}

type UserRepo struct {
	BaseCrudRepo[models.User, models.UserDTO, models.UserPage]
}

func NewUserRepo(db *gorm.DB) *UserRepo {
	return &UserRepo{
		BaseCrudRepo: BaseCrudRepo[models.User, models.UserDTO, models.UserPage]{
			db:        db,
			pageQuery: userPageQuery,
		},
	}
}

func (r *UserRepo) GetByUsernameOrEmail(username string) (models.UserDTO, error) {
	var user models.UserDTO
	err := r.db.Where("(username = ? OR email = ?)", username, username).First(&user).Error
	return user, err
}

func (r *UserRepo) GetOrgPermissions(id any, orgID any) ([]string, error) {
	var permissions []string
	query := `
		select
			distinct rp."permission" as permissions
		from roles r
		left join role_permissions rp on r.id = rp.role_id 
		left join user_roles ur on r.id = ur.role_id
		where r.organization_id = ?
		and ur.user_id = ?
		and rp.deleted_at isnull
		and ur.deleted_at isnull
	`

	err := r.db.Raw(query, orgID, id).Pluck("permissions", &permissions).Error
	return permissions, err
}

func (r *UserRepo) GetPermissions(id any) ([]models.OrganizationPermissionClaims, error) {
	var orgPermissions []models.OrganizationPermissionClaims
	query := `
		select
			r.organization_id as org_id,
			string_agg(rp."permission", ';') as permissions
		from roles r
		left join role_permissions rp on r.id = rp.role_id 
		left join user_roles ur on r.id = ur.role_id
		where ur.user_id = ?
		and rp.deleted_at isnull
		and ur.deleted_at isnull
		group by r.organization_id 
	`

	err := r.db.Raw(query, id).Scan(&orgPermissions).Error
	return orgPermissions, err
}
