// This file is auto generated by polygo
package middlewares

import (
	"strconv"
	"strings"

	"github.com/MarcelArt/multi-tenant-system/models"
	"github.com/MarcelArt/multi-tenant-system/pkg/arrays"
	"github.com/MarcelArt/multi-tenant-system/pkg/objects"
	"github.com/MarcelArt/multi-tenant-system/repositories"
	"github.com/MarcelArt/multi-tenant-system/utils"
	"github.com/gofiber/fiber/v2"
)

type AuthMiddleware struct {
	uRepo repositories.IUserRepo
}

func NewAuthMiddleware(uRepo repositories.IUserRepo) *AuthMiddleware {
	return &AuthMiddleware{
		uRepo: uRepo,
	}
}

func (m *AuthMiddleware) ProtectedAPI(c *fiber.Ctx) error {
	token := c.Get("Authorization")
	idToken := strings.TrimSpace(strings.Replace(token, "Bearer", "", 1))
	claims, err := utils.ParseToken(idToken)
	if err != nil {
		return c.Status(fiber.StatusUnauthorized).JSON(models.NewJSONResponse(err, ""))
	}

	c.Locals("userId", claims["userId"])
	c.Locals("orgPerms", claims["orgPerms"])
	return c.Next()
}

func (m *AuthMiddleware) Authz(permissionKey string) fiber.Handler {
	return func(c *fiber.Ctx) error {
		orgIDStr := c.Params("org_id")
		orgID, err := strconv.Atoi(orgIDStr)
		if err != nil {
			return c.Status(fiber.StatusBadRequest).JSON(models.NewJSONResponse(err, "invalid organization id"))
		}

		var orgPerms []models.OrganizationPermissionClaims
		if err := objects.Cast(c.Locals("orgPerms"), &orgPerms); err != nil {
			return c.Status(fiber.StatusForbidden).JSON(models.NewJSONResponse(err, "invalid permissions"))
		}

		currentPerm := arrays.Find(orgPerms, func(orgPerm models.OrganizationPermissionClaims) bool {
			return orgPerm.OrgID == uint(orgID)
		})

		permissions := strings.Split(currentPerm.Permissions, ";")
		permission := arrays.Find(permissions, func(p string) bool {
			return p == permissionKey
		})

		if permission == nil {
			return c.Status(fiber.StatusForbidden).JSON(models.NewJSONResponse(nil, "access denied"))
		}

		return c.Next()
	}
}
