// This file is auto generated by polygo
package config

import (
	"log"
	"os"
	"strconv"

	"github.com/joho/godotenv"
)

type env struct {
	PORT                        string
	DBPort                      string
	DBUser                      string
	DBPassword                  string
	DBName                      string
	DBHost                      string
	DBSchema                    string
	JwtSecret                   string
	JwtAccessTokenExpiryMinutes int
	ServerENV                   string
}

var Env *env

func SetupENV() {
	err := godotenv.Load(".env")
	if err != nil {
		log.Panic(err.Error())
	}

	jwtAccessTokenExpiryMinutes, err := strconv.Atoi(os.Getenv("JWT_ACCESS_TOKEN_EXPIRY_MINUTES"))
	if err != nil {
		jwtAccessTokenExpiryMinutes = 5
	}

	Env = &env{
		PORT:                        os.Getenv("PORT"),
		DBPort:                      os.Getenv("DB_PORT"),
		DBUser:                      os.Getenv("DB_USER"),
		DBPassword:                  os.Getenv("DB_PASSWORD"),
		DBName:                      os.Getenv("DB_NAME"),
		DBHost:                      os.Getenv("DB_HOST"),
		DBSchema:                    os.Getenv("DB_SCHEMA"),
		JwtSecret:                   os.Getenv("JWT_SECRET"),
		JwtAccessTokenExpiryMinutes: jwtAccessTokenExpiryMinutes,
		ServerENV:                   os.Getenv("SERVER_ENV"),
	}
}
