// This file is auto generated by polygo
package cmd

import (
	"fmt"
	"os"
)

func Manager(args []string) {
	argsLength := len(args)
	fn := args[1]
	switch fn {
	case "migrate":
		if argsLength < 3 {
			fmt.Println("Please input up or down")
			os.Exit(1)
		}
		Migrate(args[2])
	default:
		fmt.Println("Unknown command")
		os.Exit(1)
	}
}
