// This file is auto generated by polygo
package cmd

import (
	"os"

	"github.com/MarcelArt/multi-tenant-system/config"
	"github.com/MarcelArt/multi-tenant-system/database"
)

func Migrate(arg string) {
	switch arg {
	case "up":
		config.SetupENV()
		database.ConnectDB()
		database.MigrateDB()
	case "down":
		config.SetupENV()
		database.ConnectDB()
		database.DropDB()
	default:
		println("Unknown command")
		os.Exit(1)
	}
}

