// This file is auto generated by polygo
package api_handlers

import (
	"github.com/MarcelArt/multi-tenant-system/models"
	"github.com/MarcelArt/multi-tenant-system/repositories"
	"github.com/MarcelArt/multi-tenant-system/utils"
	"github.com/go-playground/validator/v10"
	"github.com/gofiber/fiber/v2"
)

type OrgCrudHandler[TModel any, TDto models.IDTO, TPage any] struct {
	repo      repositories.IOrgCrudRepo[TModel, TDto, TPage]
	validator *validator.Validate
}

func (h *OrgCrudHandler[TModel, TDto, TPage]) Create(c *fiber.Ctx) error {
	var dto TDto

	if err := c.BodyParser(&dto); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(models.NewJSONResponse(err, ""))
	}

	if err := h.validator.Struct(dto); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(models.NewJSONResponse(err, ""))
	}

	id, err := h.repo.Create(dto)
	if err != nil {
		return c.Status(utils.StatusCodeByError(err)).JSON(models.NewJSONResponse(err, ""))
	}

	return c.Status(fiber.StatusCreated).JSON(models.NewJSONResponse(fiber.Map{"ID": id}, "Created successfully"))
}

func (h *OrgCrudHandler[TModel, TDto, TPage]) Read(c *fiber.Ctx) error {
	orgID := c.Params("org_id")
	var dest []TPage

	page := h.repo.Read(c, orgID, dest)

	return c.Status(fiber.StatusOK).JSON(page)
}

func (h *OrgCrudHandler[TModel, TDto, TPage]) Update(c *fiber.Ctx) error {
	id := c.Params("id")
	orgID := c.Params("org_id")

	var dto TDto

	if err := c.BodyParser(&dto); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(models.NewJSONResponse(err, ""))
	}

	if err := h.validator.Struct(dto); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(models.NewJSONResponse(err, ""))
	}

	if err := h.repo.Update(id, orgID, &dto); err != nil {
		return c.Status(utils.StatusCodeByError(err)).JSON(models.NewJSONResponse(err, ""))
	}

	return c.Status(fiber.StatusOK).JSON(dto)
}

func (h *OrgCrudHandler[TModel, TDto, TPage]) Delete(c *fiber.Ctx) error {
	id := c.Params("id")
	orgID := c.Params("org_id")

	model, err := h.repo.Delete(id, orgID)

	if err != nil {
		return c.Status(utils.StatusCodeByError(err)).JSON(models.NewJSONResponse(err, ""))
	}

	return c.Status(fiber.StatusOK).JSON(models.NewJSONResponse(model, "Deleted successfully"))
}

func (h *OrgCrudHandler[TModel, TDto, TPage]) GetByID(c *fiber.Ctx) error {
	id := c.Params("id")
	orgID := c.Params("org_id")

	model, err := h.repo.GetByID(id, orgID)

	if err != nil {
		return c.Status(utils.StatusCodeByError(err)).JSON(models.NewJSONResponse(err, ""))
	}

	return c.Status(fiber.StatusOK).JSON(models.NewJSONResponse(model, "Data retrieved successfully"))
}
