/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as RolesIndexRouteImport } from './routes/roles.index'
import { Route as AccessLogsIndexRouteImport } from './routes/access-logs.index'
import { Route as OrganizationSettingRouteImport } from './routes/organization.setting'
import { Route as OrganizationMembersRouteImport } from './routes/organization.members'
import { Route as OrganizationCreateRouteImport } from './routes/organization.create'
import { Route as UsersUpdateIdRouteImport } from './routes/users.update.$id'
import { Route as RolesUpdateIdRouteImport } from './routes/roles.update.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessLogsIndexRoute = AccessLogsIndexRouteImport.update({
  id: '/access-logs/',
  path: '/access-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSettingRoute = OrganizationSettingRouteImport.update({
  id: '/organization/setting',
  path: '/organization/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationMembersRoute = OrganizationMembersRouteImport.update({
  id: '/organization/members',
  path: '/organization/members',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationCreateRoute = OrganizationCreateRouteImport.update({
  id: '/organization/create',
  path: '/organization/create',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUpdateIdRoute = UsersUpdateIdRouteImport.update({
  id: '/users/update/$id',
  path: '/users/update/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesUpdateIdRoute = RolesUpdateIdRouteImport.update({
  id: '/roles/update/$id',
  path: '/roles/update/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/setting': typeof OrganizationSettingRoute
  '/access-logs': typeof AccessLogsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/users': typeof UsersIndexRoute
  '/roles/update/$id': typeof RolesUpdateIdRoute
  '/users/update/$id': typeof UsersUpdateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/setting': typeof OrganizationSettingRoute
  '/access-logs': typeof AccessLogsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/users': typeof UsersIndexRoute
  '/roles/update/$id': typeof RolesUpdateIdRoute
  '/users/update/$id': typeof UsersUpdateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/organization/create': typeof OrganizationCreateRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/setting': typeof OrganizationSettingRoute
  '/access-logs/': typeof AccessLogsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/roles/update/$id': typeof RolesUpdateIdRoute
  '/users/update/$id': typeof UsersUpdateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/organization/create'
    | '/organization/members'
    | '/organization/setting'
    | '/access-logs'
    | '/roles'
    | '/users'
    | '/roles/update/$id'
    | '/users/update/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/organization/create'
    | '/organization/members'
    | '/organization/setting'
    | '/access-logs'
    | '/roles'
    | '/users'
    | '/roles/update/$id'
    | '/users/update/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/organization/create'
    | '/organization/members'
    | '/organization/setting'
    | '/access-logs/'
    | '/roles/'
    | '/users/'
    | '/roles/update/$id'
    | '/users/update/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  OrganizationCreateRoute: typeof OrganizationCreateRoute
  OrganizationMembersRoute: typeof OrganizationMembersRoute
  OrganizationSettingRoute: typeof OrganizationSettingRoute
  AccessLogsIndexRoute: typeof AccessLogsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  RolesUpdateIdRoute: typeof RolesUpdateIdRoute
  UsersUpdateIdRoute: typeof UsersUpdateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-logs/': {
      id: '/access-logs/'
      path: '/access-logs'
      fullPath: '/access-logs'
      preLoaderRoute: typeof AccessLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/setting': {
      id: '/organization/setting'
      path: '/organization/setting'
      fullPath: '/organization/setting'
      preLoaderRoute: typeof OrganizationSettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/members': {
      id: '/organization/members'
      path: '/organization/members'
      fullPath: '/organization/members'
      preLoaderRoute: typeof OrganizationMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/create': {
      id: '/organization/create'
      path: '/organization/create'
      fullPath: '/organization/create'
      preLoaderRoute: typeof OrganizationCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/update/$id': {
      id: '/users/update/$id'
      path: '/users/update/$id'
      fullPath: '/users/update/$id'
      preLoaderRoute: typeof UsersUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/update/$id': {
      id: '/roles/update/$id'
      path: '/roles/update/$id'
      fullPath: '/roles/update/$id'
      preLoaderRoute: typeof RolesUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  OrganizationCreateRoute: OrganizationCreateRoute,
  OrganizationMembersRoute: OrganizationMembersRoute,
  OrganizationSettingRoute: OrganizationSettingRoute,
  AccessLogsIndexRoute: AccessLogsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  RolesUpdateIdRoute: RolesUpdateIdRoute,
  UsersUpdateIdRoute: UsersUpdateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
