// This file is auto generated by polygo
package models

import (
	"time"
)

type IDTO interface {
	GetID() uint
}

type DTO struct {
	ID        uint      `gorm:"primarykey" json:"-"`
	CreatedAt time.Time `json:"-"`
	UpdatedAt time.Time `json:"-"`
}

func (d DTO) GetID() uint {
	return d.ID
}

// type IOrgDTO interface {
// 	GetID() uint
// 	SetOrganizationID(orgID uint) OrgDTO
// }

// type OrgDTO struct {
// 	ID             uint      `gorm:"primarykey" json:"-"`
// 	CreatedAt      time.Time `json:"-"`
// 	UpdatedAt      time.Time `json:"-"`
// 	OrganizationID uint      `gorm:"not null" json:"organizationId"`
// }

// func (d OrgDTO) GetID() uint {
// 	return d.ID
// }

// func (d OrgDTO) SetOrganizationID(orgID uint) OrgDTO {
// 	d.OrganizationID = orgID
// 	return d
// }
