// This file is auto generated by polygo
package models

import (
	"time"

	"github.com/MarcelArt/multi-tenant-system/enums"
	"github.com/golang-jwt/jwt/v5"
	"gorm.io/gorm"
)

const userTableName = "users"

type User struct {
	gorm.Model
	Username string `json:"username" gorm:"unique;not null"`
	Email    string `json:"email" gorm:"unique;not null" validate:"email"`
	Password string `json:"-" gorm:"not null" validate:"min=8"`
}

type UserDTO struct {
	DTO
	Username string `json:"username" gorm:"unique;not null"`
	Email    string `json:"email" gorm:"unique;not null" validate:"email"`
	Password string `json:"password" gorm:"not null" validate:"min=8"`
}

type UserPage struct {
	Username string `json:"username" gorm:"unique;not null"`
	Email    string `json:"email" gorm:"unique;not null" validate:"email"`
}

type LoginInput struct {
	Username   string `json:"username" gorm:"unique;not null"`
	Password   string `json:"password" gorm:"not null" validate:"min=8"`
	IsRemember bool   `json:"isRemember"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	UserID       uint   `json:"userId"`
	Email        string `json:"email"`
	Username     string `json:"username"`
}

type RefreshInput struct {
	RefreshToken string `json:"refreshToken" validate:"jwt"`
}

type OrganizationPermissionClaims struct {
	OrgID       uint   `json:"orgId"`
	Permissions string `json:"permissions"`
}

type UserClaims struct {
	ID       uint                           `json:"id"`
	Username string                         `json:"username"`
	OrgPerms []OrganizationPermissionClaims `json:"orgPerms"`
}

func (UserDTO) TableName() string {
	return userTableName
}

func (m UserDTO) AccessClaims(exp int64) jwt.MapClaims {
	return jwt.MapClaims{
		"username": m.Username,
		"userId":   m.ID,
		"exp":      exp,
	}
}

func (m UserDTO) RefreshClaims(isRemember bool) jwt.MapClaims {
	expireAt := time.Now().Add(enums.Day)
	if isRemember {
		expireAt = time.Now().Add(enums.Month)
	}
	return jwt.MapClaims{
		"userId":     m.ID,
		"isRemember": isRemember,
		"exp":        expireAt.Unix(),
	}
}

func (m UserClaims) AccessClaims(exp int64) jwt.MapClaims {
	return jwt.MapClaims{
		"username": m.Username,
		"userId":   m.ID,
		"sub":      m.ID,
		"exp":      exp,
		"orgPerms": m.OrgPerms,
	}
}

func (m UserClaims) RefreshClaims(isRemember bool) jwt.MapClaims {
	expireAt := time.Now().Add(enums.Day)
	if isRemember {
		expireAt = time.Now().Add(enums.Month)
	}
	return jwt.MapClaims{
		"userId":     m.ID,
		"sub":        m.ID,
		"isRemember": isRemember,
		"exp":        expireAt.Unix(),
	}
}
